### ISSUE TITLE
Feedback for “Making a Multiplayer Game”

### ISSUE THREAD

**Issue by felipej26** [asadm/playroom-docs#17]
Hi everyone,
I have a question, do you have plans to release the API or a SDK for React Native?
I have an RN app and would like to use Playroom to create some multiplayer features.

**Comment by asadm** [comment]
Hey sorry for missing this. We dont yet have a plan for that. One workaround would be to use WebView in React Native to load playroom library in a headless browser and then interact with it via bridge.
